name: Upload Container To Cloud

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.REGISTRY_SERVER}}
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - name: Build and push
              run: |
                  docker build . -t ${{secrets.REGISTRY_SERVER}}/kriyeta:latest
                  docker push ${{secrets.REGISTRY_SERVER}}/kriyeta:latest
